name: Updater (WIP)

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    if: github.repository_owner == 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run HugoBlox updater
        uses: HugoBlox/gh-action-updater@v1
        with:
          feed-url: https://hugoblox.com/rss.xml
          readme-section: news
          branch: main
